default_install_hook_types = ["pre-commit", "pre-push"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "format"
name = "format"
entry = "pnpm run fmt"
language = "system"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "fix:ts"
name = "fix:ts"
entry = "pnpm run fix:ts"
language = "system"
files = "\\.(ts|tsx)$"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "fix:rs"
name = "fix:rs"
entry = "pnpm run fix:rs"
language = "system"
files = "^game-server/.*\\.rs$"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "test"
name = "test"
entry = "pnpm run test"
language = "system"
files = "\\.(rs|ts|tsx)$"
pass_filenames = false
stages = ["pre-push"]
