package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"

	"github.com/toxeeec/chess/services/go/gateway/graph/model"
)

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context, input model.PingInput) (model.PingResponse, error) {
	return model.PingResponse{Text: input.Text}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
