// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JoinGameResponse struct {
	Fen    string   `json:"fen"`
	Result *float64 `json:"result"`
	Moves  []string `json:"moves"`
}

type MakeMoveInput struct {
	Move string `json:"move"`
}
