// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: chess.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Chess_MakeMove_FullMethodName = "/chess.Chess/MakeMove"
	Chess_JoinGame_FullMethodName = "/chess.Chess/JoinGame"
)

// ChessClient is the client API for Chess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChessClient interface {
	MakeMove(ctx context.Context, in *MakeMoveRequest, opts ...grpc.CallOption) (*MakeMoveResponse, error)
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (Chess_JoinGameClient, error)
}

type chessClient struct {
	cc grpc.ClientConnInterface
}

func NewChessClient(cc grpc.ClientConnInterface) ChessClient {
	return &chessClient{cc}
}

func (c *chessClient) MakeMove(ctx context.Context, in *MakeMoveRequest, opts ...grpc.CallOption) (*MakeMoveResponse, error) {
	out := new(MakeMoveResponse)
	err := c.cc.Invoke(ctx, Chess_MakeMove_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (Chess_JoinGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chess_ServiceDesc.Streams[0], Chess_JoinGame_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chessJoinGameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chess_JoinGameClient interface {
	Recv() (*JoinGameResponse, error)
	grpc.ClientStream
}

type chessJoinGameClient struct {
	grpc.ClientStream
}

func (x *chessJoinGameClient) Recv() (*JoinGameResponse, error) {
	m := new(JoinGameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChessServer is the server API for Chess service.
// All implementations must embed UnimplementedChessServer
// for forward compatibility
type ChessServer interface {
	MakeMove(context.Context, *MakeMoveRequest) (*MakeMoveResponse, error)
	JoinGame(*JoinGameRequest, Chess_JoinGameServer) error
	mustEmbedUnimplementedChessServer()
}

// UnimplementedChessServer must be embedded to have forward compatible implementations.
type UnimplementedChessServer struct {
}

func (UnimplementedChessServer) MakeMove(context.Context, *MakeMoveRequest) (*MakeMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeMove not implemented")
}
func (UnimplementedChessServer) JoinGame(*JoinGameRequest, Chess_JoinGameServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedChessServer) mustEmbedUnimplementedChessServer() {}

// UnsafeChessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChessServer will
// result in compilation errors.
type UnsafeChessServer interface {
	mustEmbedUnimplementedChessServer()
}

func RegisterChessServer(s grpc.ServiceRegistrar, srv ChessServer) {
	s.RegisterService(&Chess_ServiceDesc, srv)
}

func _Chess_MakeMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServer).MakeMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chess_MakeMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServer).MakeMove(ctx, req.(*MakeMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chess_JoinGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinGameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChessServer).JoinGame(m, &chessJoinGameServer{stream})
}

type Chess_JoinGameServer interface {
	Send(*JoinGameResponse) error
	grpc.ServerStream
}

type chessJoinGameServer struct {
	grpc.ServerStream
}

func (x *chessJoinGameServer) Send(m *JoinGameResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Chess_ServiceDesc is the grpc.ServiceDesc for Chess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chess.Chess",
	HandlerType: (*ChessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeMove",
			Handler:    _Chess_MakeMove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinGame",
			Handler:       _Chess_JoinGame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chess.proto",
}
