/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomIdRouteImport } from './routes/$roomId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIdWsRouteImport } from './routes/$roomId.ws'

const RoomIdRoute = RoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdWsRoute = RoomIdWsRouteImport.update({
  id: '/ws',
  path: '/ws',
  getParentRoute: () => RoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRouteWithChildren
  '/$roomId/ws': typeof RoomIdWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRouteWithChildren
  '/$roomId/ws': typeof RoomIdWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRouteWithChildren
  '/$roomId/ws': typeof RoomIdWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$roomId' | '/$roomId/ws'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$roomId' | '/$roomId/ws'
  id: '__root__' | '/' | '/$roomId' | '/$roomId/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomIdRoute: typeof RoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$roomId': {
      id: '/$roomId'
      path: '/$roomId'
      fullPath: '/$roomId'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$roomId/ws': {
      id: '/$roomId/ws'
      path: '/ws'
      fullPath: '/$roomId/ws'
      preLoaderRoute: typeof RoomIdWsRouteImport
      parentRoute: typeof RoomIdRoute
    }
  }
}

interface RoomIdRouteChildren {
  RoomIdWsRoute: typeof RoomIdWsRoute
}

const RoomIdRouteChildren: RoomIdRouteChildren = {
  RoomIdWsRoute: RoomIdWsRoute,
}

const RoomIdRouteWithChildren =
  RoomIdRoute._addFileChildren(RoomIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomIdRoute: RoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
